import SwiftUI

struct Section2Quiz {
    static let questions: [Question] = [
        Question(text: "What distinguishes Cultural Appropriation from Cultural Appreciation?", options: ["A) Cultural Appropriation involves taking from a culture without respect, while Cultural Appreciation involves understanding and valuing the culture", "B) Cultural Appropriation is always intentional, whereas Cultural Appreciation is not", "C) Cultural Appropriation is legally prohibited, while Cultural Appreciation is encouraged", "D) There is no real difference; both terms are interchangeable"], answer: "A) Cultural Appropriation involves taking from a culture without respect, while Cultural Appreciation involves understanding and valuing the culture"),
        Question(text: "What is Implicit Bias?", options: ["A) A bias that is openly expressed and intentional", "B) A bias that occurs unconsciously and affects decisions and behaviors", "C) A type of bias that only affects certain groups of people", "D) A bias that can be easily corrected through awareness alone"], answer: "B) A bias that occurs unconsciously and affects decisions and behaviors"),
        Question(text: "What does Racial Insensitivity refer to?", options: ["A) Being overly sensitive about racial issues", "B) Intentionally offending a race by mocking their culture", "C) Unintentionally offending a race by mocking their culture", "D) Acknowledging racial differences in a respectful manner"], answer: "C) Unintentionally offending a race by mocking their culture"),
        Question(text: "How do Nationality and Ethnicity differ?", options: ["A) Nationality is based on where you live, while Ethnicity is based on cultural identity", "B) Nationality can change, but Ethnicity cannot", "C) Ethnicity is determined by your language, while Nationality is not", "D) They are the same thing"], answer: "A) Nationality is based on where you live, while Ethnicity is based on cultural identity"),
        Question(text: "Cultural Appreciation is similar to which concept?", options: ["A) Cultural Appropriation", "B) Cultural Relativism", "C) Implicit Bias", "D) Racial Insensitivity"], answer: "B) Cultural Relativism"),
        Question(text: "How does Implicit Bias affect our behavior?", options: ["A) It ensures fairness in our judgments and decisions", "B) It has no impact on our behavior since it's unconscious", "C) It can lead to unintentional discrimination and unfair judgments", "D) It only affects those who are aware of their biases"], answer: "C) It can lead to unintentional discrimination and unfair judgments"),
        Question(text: "How does Implicit Bias affect our behavior?", options: ["A) It ensures fairness in our judgments and decisions", "B) It has no impact on our behavior since it's unconscious", "C) It can lead to unintentional discrimination and unfair judgments", "D) It only affects those who are aware of their biases"], answer: "C) It can lead to unintentional discrimination and unfair judgments"),
        Question(text: "How can one address Racial Insensitivity in a constructive way?", options: ["A) By ignoring insensitive remarks to avoid conflict", "B) Through education and open dialogue about the impact of such remarks", "C) By encouraging more insensitive jokes to desensitize people", "D) Racial Insensitivity cannot be addressed"], answer: "B) Through education and open dialogue about the impact of such remarks"),
        Question(text: "Which of the following is an example of Cultural Appreciation?", options: ["A) Wearing a culturally significant outfit as a fashion statement without understanding its meaning", "B) Learning a language to better communicate and understand a culture", "C) Using cultural symbols in personal branding without acknowledgment", "D) Selling artifacts from another culture for profit without giving back to the community"], answer: "B) Learning a language to better communicate and understand a culture"),
        Question(text: "What can be a negative outcome of Cultural Appropriation?", options: ["A) It can lead to greater cultural understanding and appreciation", "B) It may result in the commodification and disrespect of sacred cultural practices", "C) It increases the cultural diversity in fashion and art without any drawbacks", "D) It encourages people from different cultures to share their heritage freely"], answer: "B) It may result in the commodification and disrespect of sacred cultural practices"),
        Question(text: "Why is it important to understand the difference between nationality and ethnicity?", options: ["A) To navigate legal and citizenship issues accurately", "B) Understanding these differences helps in appreciating cultural diversity and fostering inclusivity", "C) It is only important for academic and research purposes", "D) Nationality and ethnicity are interchangeable, so understanding the difference is not necessary"], answer: "B) Understanding these differences helps in appreciating cultural diversity and fostering inclusivity")
  ]
}

