// Section1의 문제와 답.
// 반드시 수정.

import SwiftUI

struct Section1Quiz {
    static let questions: [Question] = [
        Question(text: "What is a beneficial first step to stop racism in the classroom?", options: ["A) Ignore the differences between students", "B) Learn about different cultures and traditions", "C) Only associate with people like yourself", "D) Avoid discussing any cultural topics"], answer: "B) Learn about different cultures and traditions"),
        Question(text: "If you hear a classmate making a racist remark, what should you do?", options: ["A) Join in to fit in with the group", "B) Stay silent and ignore it", "C) Report it to a trusted adult like a teacher or family member", "D) Laugh it off as a joke"], answer: "C) Report it to a trusted adult like a teacher or family member"),
        Question(text: "How can student-led clubs like SOAR (Student Organized Against Racism) help combat racism?", options: ["A) By segregating students based on their backgrounds", "B) Through exclusive membership and secretive meetings", "C) By providing safe spaces for discussion and sharing experiences", "D) By allowing only certain students to voice their opinions"], answer: "C) By providing safe spaces for discussion and sharing experiences"),
        Question(text: "What is a direct way to support a classmate who has experienced racism?", options: ["A) Advise them to forget about the incident", "B) Listen to their experience and accompany them to report the incident", "C) Tell them it's a part of life and to get used to it", "D) Encourage them to retaliate"], answer: "B) Listen to their experience and accompany them to report the incident"),
        Question(text: "What is an essential aspect of discussing racism in schools?" , options: ["A) Speaking over others to make sure your voice is heard", "B) Only listening to people who agree with you", "C) Understanding different perspectives and the history of racism", "D) Focusing solely on the positive aspects of history"], answer: "C) Understanding different perspectives and the history of racism"),
        Question(text: "Why is it important to challenge racial stereotypes in the classroom?", options: ["A) To conform to school policies", "B) To ensure that everyone fits a standard profile", "C) To promote a deeper understanding of individuality and reduce prejudice", "D) To reinforce traditional viewpoints"], answer: "C) To promote a deeper understanding of individuality and reduce prejudice"),
        Question(text: "How should a school respond if a teacher observes an act of racism among students?", options: ["A) By ignoring it to avoid conflict", "B) By addressing it privately with the students involved only", "C) By using it as a teachable moment and discussing it openly in class", "D) By immediately expelling the student who made the racist remark"], answer: "C) By using it as a teachable moment and discussing it openly in class"),
        Question(text: "What role can inclusive teaching materials play in the fight against racism?", options: ["A) They have no impact on students’ understanding of racism", "B) They can help to perpetuate existing stereotypes", "C) They can expose students to a wider range of perspectives and encourage empathy", "D) They should only include majority culture perspectives to avoid controversy"], answer: "C) They can expose students to a wider range of perspectives and encourage empathy"),
        Question(text: "In what way can students actively participate in creating an inclusive school environment?", options: ["A) By organizing and attending diversity and inclusion training workshops", "B) By waiting for school administrators to take action", "C) By only socializing with their immediate circle of friends", "D) By avoiding conversations about race to prevent discomfort"], answer: "A) By organizing and attending diversity and inclusion training workshops"),
        Question(text: "How can schools effectively support students from diverse backgrounds?", options: ["A) By treating all students the same and ignoring cultural differences", "B) By only celebrating the most common cultural holidays", "C) By creating policies that specifically prohibit discriminatory behavior", "D) By assuming that students from diverse backgrounds do not need any additional support"], answer: "C) By creating policies that specifically prohibit discriminatory behavior")
        
    ]
}

